#!/bin/bash

echo "==========================================="
echo "  Kyra Dashboard Access Information"
echo "==========================================="
echo ""
echo "The Kyra Dashboard is now running!"
echo ""
echo "Access the dashboard at:"
echo "  http://localhost:3001"
echo ""
echo "API endpoints are available at:"
echo "  http://localhost:3001/api/*"
echo ""
echo "Features available:"
echo "- Real-time chat interface with Kyra"
echo "- Always-active terminal for remote commands"
echo "- Lead management and monitoring"
echo "- System status and metrics"
echo ""
echo "To stop the server, press Ctrl+C in the server terminal"
echo "==========================================="